name: Jekyll Build

on:
  push:
    branches: [main] # Or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # Compatible with jekyll-scholar
          bundler-cache: true

      # Set up Python and install Jupyter before running the build
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Jupyter
        run: pip install jupyter

      - name: Install dependencies
        run: bundle install
