name: 'Lighthouse-Badger-Easy'

########################################################################
# DEFINE INPUTS AND TRIGGERS
########################################################################

env:
  URLS: https://nikos6ares.github.io/  # URL(s) to test
  TOKEN_NAME: LIGHTHOUSE_BADGER_TOKEN  # Token name (NO VALUE!)
  REPO_BRANCH: '${{ github.repository }} main'  # Target repo & branch

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URL(s) to be checked'
        required: true
      token_name:
        description: 'Target token name (NO VALUE!)'
        required: true

########################################################################
# PERMISSIONS & JOBS
########################################################################

permissions:
  contents: write  # Required to push badges to the repo

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-22.04
    timeout-minutes: 8
    steps:
      # Step 1: Set up repo/branch vars
      - name: Preparatory Tasks
        run: |
          REPOSITORY=`expr "${{ env.REPO_BRANCH }}" : "\([^ ]*\)"`
          BRANCH=`expr "${{ env.REPO_BRANCH }}" : ".* \([^ ]*\)"`
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      # Step 2: Checkout YOUR repo (with correct token)
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets.LIGHTHOUSE_BADGER_TOKEN }}
          ref: ${{ env.BRANCH }}

      # Step 3: Checkout Lighthouse Badges tool
      - name: Checkout Lighthouse Badges
        uses: actions/checkout@v4
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested

      # Step 4: Run Lighthouse Badger
      - name: Run Lighthouse Badger
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ github.event.inputs.urls || env.URLS }}
